baseURL = 'https://willscyber.net/'
languageCode = 'en-us'
title = "Will's CYBER WAREHOUSE"
theme = "mainroad"
publishDir = "public"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "tools"
    name = "Tools"
    url = "/tools/"
    weight = 30

  [[menu.main]]
    identifier = "bookmarks"
    name = "Booksmarks"
    url = "/bookmarks/"
    weight = 40




# If you're deploying from the `hugo` branch
[deployment]
  [[deployment.targets]]
    name = "github"
    URL = "https://github.com/PersonalComputerRetailer/test2023.git"
    branch = "hugo"
    target = "public"

[markup.goldmark.renderer]
unsafe = true

[params]
  author = "WILL"
  description = "Tech notes, experiments, and thoughts from my cyber warehouse."

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services]
  [services.googleAnalytics]
    id = "G-6XELVJJ51M"
