baseURL = 'https://willscyber.net/'
languageCode = 'en-us'
title = 'Wills CYBER WAREHOUSE'
theme = "PaperMod"
publishDir = "public"

# If you're deploying from the `hugo` branch
[deployment]
  [[deployment.targets]]
    name = "github"
    URL = "https://github.com/PersonalComputerRetailer/test2023.git"
    branch = "hugo"
    target = "public"

[params]
  author = "WILL"
  description = "Tech notes, experiments, and thoughts from my cyber warehouse."

[caches]
  [caches.images]
    dir = ':cacheDir/images'
